### PR TITLE
Fix: display correct reason on Failure Screen if coming from a Bonus Question

### LINKED ISSUE #103: Failure screen not displaying the correct reason on bonus question failure
### Expected Behaviour
The failure screen shows the correct reason when a bonus question is answered incorrectly.

### Actual Behaviour
The bonus question shows the reason based on the normal question failure, e.g., that "The Shining" is incorrect and it should be "The Shining".

### Steps to Reproduce the Issue
- Answer a bonus question incorrectly

### PR DESCRIPTION
**Pull request by nikzaugg**
### Description

* display correct reason on Failure Screen if coming from a Bonus Question
* redo styling of `BonusQuestion.tsx`

image

image

### Related Issues

#103 

### Checklist

- [x] Have you added tests where necessary? Do all the test pass? 
- [x] Have you added descriptive comments to your code?
- [x] Have you updated the documentation related to this propo

### CODE REVIEW

File: src/pages/Failure.tsx [hunk 1]
```diff
@@ -7,6 +7,7 @@ import {
 import emoji from 'node-emoji'
 import React, { useRef, useState } from 'react'
 import { useHistory } from 'react-router'
+import { useLastLocation } from 'react-router-last-location'
```
Comment (rschlaefli) [inline src/pages/Failure.tsx:10]: Nice lib!

**Review by rschlaefli — APPROVED** [review]
LGTM ;)
