### PR TITLE
Fix: Double Points Animation

### LINKED ISSUE #104: Double-execution of Points Animations
### Description

The animations related to points sometimes execute twice (another time when the screen is left using "Gamble" for example). I am not sure whether the points are also added twice, or if it is only the animation, but I had the feeling that points calculations were off sometimes as well.

### PR DESCRIPTION
**Pull request by nikzaugg**
### Description
Removes the "additional" animation when leaving the success screen and going to the Game Screen. This was due to adding the points before leaving, which triggered a new animation

### Related Issues

#104 

### Checklist

- [x] Have you added tests where necessary? Do all the test pass? 
- [x] Have you added descriptive comments to your code?
- [x] Have you updated the documentation related to this PR

### CODE REVIEW

File: src/pages/Success.tsx [hunk 1]
```diff
@@ -79,7 +79,6 @@ const Success = () => {
   }
 
   const gotToBonusQuestion = () => {
-    addPoints(pointDifference)
```
Comment (nikzaugg) [inline src/pages/Success.tsx:86]: If we go to the Bonus Question, we don't add points instantly

File: src/pages/BonusQuestion.tsx [hunk 2]
```diff
@@ -21,7 +25,11 @@ const GET_BONUS_SCORE = gql`
 const BonusQuestion = () => {
   const history = useHistory()
 
-  const { setPointDifference, pointDifference } = useStore()
+  const { setPointDifference, pointDifference, addPoints } = useStore()
+
+  useIonViewWillEnter(() => {
+    addPoints(pointDifference)
```
Comment (nikzaugg) [inline src/pages/BonusQuestion.tsx:31]: points are added upon entering the BonusQuestion screen, this should solve the animation issue

**Review by rschlaefli — APPROVED** [review]
